FROM php:apache

RUN a2enmod rewrite
# RUN a2enmod ssl && a2enmod rewrite && a2enmod autoindex
# RUN mkdir -p /etc/apache2/ssl
# RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

# COPY ./ssl/*.pem /etc/apache2/ssl/
# COPY ./apache/000-default.conf /etc/apache2/sites-available/000-default.conf

# EXPOSE 80