version: "3.9"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    # restart: unless-stopped
    restart: on-failure
    # restart: always
    # tty: true
    ports:
      - 27017:27017
    volumes:
      - mongo_volume:/data/db
    environment:
      # MONGO_INITDB_ROOT_USERNAME: mongo
      # MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - internal

volumes:
  mongo_volume:
networks:
  internal:
    driver: bridge
